      SUBROUTINE ISOMAT(SSEISO,DISO,C10,CBARI1)
C>     ISOTROPIC MATRIX : ISOCHORIC SEF AND DERIVATIVES
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      DOUBLE PRECISION SSEISO,DISO(5)
      DOUBLE PRECISION C10,CBARI1,CBARI2
C
      SSEISO=C10*(CBARI1-THREE)
C
      !FIRST DERIVATIVE OF SSEISO IN ORDER TO I1
      DISO(1)=C10
      !FIRST DERIVATIVE OF SSEISO IN ORDER TO I2
      DISO(2)=ZERO
      !SECOND DERIVATIVE OF SSEISO IN ORDER TO I1
      DISO(3)=ZERO
      !SECOND DERIVATIVE OF SSEISO IN ORDER TO I2
      DISO(4)=ZERO
      !SECOND DERIVATIVE OF SSEISO IN ORDER TO I1 AND I2
      DISO(5)=ZERO
C
      RETURN
      END SUBROUTINE ISOMAT
