      SUBROUTINE AFFACTNETFIC(SFIC,CFIC,F,MF0,RW,FILPROPS,AFFPROPS,RU0,
     1                         DTIME,FRAC,EFI,NOEL,VARA,DIRMAX,DET,NDI)
C>    AFFINE NETWORK: 'FICTICIOUS' CAUCHY STRESS AND ELASTICITY TENSOR 
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      INTEGER NDI,I1,J1,K1,L1,M1,NOEL,IM1
      DOUBLE PRECISION SFIC(NDI,NDI),SFILFIC(NDI,NDI),
     1                  CFIC(NDI,NDI,NDI,NDI),F(NDI,NDI),MF0(NWP,NDI),
     2                 RW(NWP),CFILFIC(NDI,NDI,NDI,NDI)
      DOUBLE PRECISION FILPROPS(8),AFFPROPS(4),MFI(NDI),MF0I(NDI)
      DOUBLE PRECISION DET,AUX,PI,LAMBDAI,DWI,DDWI,RWI,LAMBDAIC
      DOUBLE PRECISION L,R0,MU0,B0,BETA,LAMBDA0,RHO,M,FI,FFI,DTIME
      DOUBLE PRECISION R0F,R0C,ETAC,LAMBDAIF,LAMBDAICL
      DOUBLE PRECISION B,FRIC,FFMAX,ANG,EFI,FRAC(4),RU0(NWP),RU
      DOUBLE PRECISION VARA,AVGA,MAXA,AUX0,FFIC,SUMA,RHO0,DIRMAX(NDI)
      
C
C     FILAMENT
      L       = FILPROPS(1)
      R0F     = FILPROPS(2)
      R0C     = FILPROPS(3)
      ETAC    = FILPROPS(4)
      MU0     = FILPROPS(5)
      BETA    = FILPROPS(6)
      B0      = FILPROPS(7)
      LAMBDA0 = FILPROPS(8)
C     NETWORK
      M       = AFFPROPS(1)
      B       = AFFPROPS(2)
      FRIC    = AFFPROPS(3)
      FFMAX   = AFFPROPS(4)
C
      PI=FOUR*ATAN(ONE)
      AUX=M*(DET**(-ONE))*FOUR*PI
      CFIC=ZERO
      SFIC=ZERO
C      
       RHO=ONE
       R0=R0F+R0C
C       
       AVGA=ZERO
       MAXA=ZERO
       SUMA=ZERO
       DIRMAX=ZERO
C       CALL DENSITY(RHO0,ZERO,B,EFI)
C        
C             OPEN (UNIT=20,FILE="projfil.out",action="write",
C     1 status="replace")
     
C        LOOP OVER THE INTEGRATION DIRECTIONS
      DO I1=1,NWP
C
       MFI=ZERO
       MF0I=ZERO
       DO J1=1,NDI
        MF0I(J1)=MF0(I1,J1)
       END DO
       RWI=RW(I1)
C
       CALL DEFFIL(LAMBDAI,MFI,MF0I,F,NDI)
C
       IF((ETAC.GT.ZERO).AND.(ETAC.LT.ONE))THEN
C
         LAMBDAIF=ETAC*(R0/R0F)*(LAMBDAI-ONE)+ONE
         LAMBDAICL=(LAMBDAI*R0-LAMBDAIF*R0F)/R0C
       ELSE
         LAMBDAIF=LAMBDAI
         LAMBDAICL=ZERO
       ENDIF   
C
       RU=RU0(I1)
       CALL CONTRACTILE(FI,FFI,DWI,DDWI,FFIC,RU,RU,LAMBDAIC,LAMBDAIF,
     1                LAMBDA0,L,R0,MU0,BETA,B0,FFMAX,FRIC,FRAC,DTIME)       
       RU0(I1)=RU
       write(*,*) i1,     LAMBDAIF, ru
C        
       CALL BANGLE(ANG,F,MFI,NOEL,NDI)
C      
       CALL DENSITY(RHO,ANG,B,EFI)
C
C        AUX0=(FFIC/FFMAX)*(RHO)
        AUX0=RU*RHO
C
        IF (RU.GT.ZERO) THEN
C        AVERAGE CONTRACTION LEVEL
         AVGA=AVGA+AUX0
         SUMA=SUMA+ONE
        IF (AUX0.GT.MAXA) THEN
C        MAXIMUM CONTRACTION LEVEL
         MAXA = AUX0
         DIRMAX=MFI
         IM1=I1
        ENDIF
        ENDIF
C       
        CALL SIGFILFIC(SFILFIC,RHO,LAMBDAI,DWI,MFI,RWI,NDI)
C
        CALL CSFILFIC(CFILFIC,RHO,LAMBDAI,DWI,DDWI,MFI,RWI,NDI)
C
C
      IF(RU.GT.ZERO)THEN      
C
       DO J1=1,NDI
        DO K1=1,NDI
         SFIC(J1,K1)=SFIC(J1,K1)+AUX*SFILFIC(J1,K1)
         DO L1=1,NDI
          DO M1=1,NDI
           CFIC(J1,K1,L1,M1)=CFIC(J1,K1,L1,M1)+AUX*CFILFIC(J1,K1,L1,M1)
          END DO
         END DO
        END DO
       END DO  
C
      ENDIF
C             
      END DO  
C      close(20)
C
        IF (SUMA.GT.ZERO) THEN
         AVGA=AVGA/NWP
        ENDIF
        VARA=(MAXA-AVGA)/MAXA
C        WRITE(*,*) VARA,MAXA,IM1,SUMA
C        
      RETURN
      END SUBROUTINE AFFACTNETFIC
