       SUBROUTINE INITIALIZE(STATEV,VV)
C
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C      
      COMMON /KFILF/FRAC0
C
C      DOUBLE PRECISION TIME(2),KSTEP
      INTEGER I1,POS,POS1,POS2,POS3,VV
      DOUBLE PRECISION STATEV(NSDV),FRAC0(NCH)
C        VISCOUS TENSORS
       DO I1=1,VV
        POS=9*I1-9
        STATEV(1+POS)=ZERO
        STATEV(2+POS)=ZERO
        STATEV(3+POS)=ZERO
        STATEV(4+POS)=ZERO
        STATEV(5+POS)=ZERO
        STATEV(6+POS)=ZERO
        STATEV(7+POS)=ZERO
        STATEV(8+POS)=ZERO
        STATEV(9+POS)=ZERO
       ENDDO
C        MYOSIN FRACTIONS AT T=0
        POS1=9*VV
       DO I1=1,NCH
        POS2=POS1+I1
        STATEV(POS2)=FRAC0(I1)
       ENDDO  
C        RELATIVE SLIDING
        DO I1=1,NWP
          POS3=POS2+I1
          STATEV(POS3)=ZERO
        ENDDO
C       DETERMINANT        
          STATEV(POS3+1)=ONE
C        CONTRACTION VARIANCE
          STATEV(POS3+2)=ZERO          
C     
      RETURN
C
      END SUBROUTINE INITIALIZE
