      SUBROUTINE DENSITY(RHO,ANG,BB,ERFI)
C>    SINGLE FILAMENT: DENSITY FUNCTION VALUE
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      DOUBLE PRECISION RHO,ANG,BB,ERFI
      DOUBLE PRECISION PI,AUX1,AUX2
C
      PI=FOUR*ATAN(ONE)
      AUX1=SQRT(BB/(TWO*PI))
      AUX2=DEXP(BB*(COS(TWO*ANG)+ONE))
      RHO=FOUR*AUX1*AUX2*(ERFI**(-ONE))
C      RHO=RHO*((FOUR*PI)**(-ONE))
C
      RETURN
      END SUBROUTINE DENSITY
