      SUBROUTINE SDVREAD(STATEV,FRAC,RU0,VV)
C>    VISCOUS DISSIPATION: READ STATE VARS
      IMPLICIT NONE
      INCLUDE 'param_umat.inc'
C
      INTEGER VV,POS1,POS2,POS3,I1
      DOUBLE PRECISION STATEV(NSDV)
      DOUBLE PRECISION FRAC(4),RU0(NWP)
C
       POS1=9*VV
       DO I1=1,4
         POS2=POS1+I1
         FRAC(I1)=STATEV(POS2)
        ENDDO
C
        DO I1=1,NWP
          POS3=POS2+I1
          RU0(I1)=STATEV(POS3)
        ENDDO
C
      RETURN
C
      END SUBROUTINE SDVREAD
