      SUBROUTINE DAMAGE(SEF,SEF0,DMG,DMGR,DMGDIFF,BETA,PSIHALF)
C>    VISCOUS DISSIPATION: READ STATE VARS
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      DOUBLE PRECISION SEF,SEF0,DMG,DMGR,DMGDIFF,BETA,PSIHALF

C     this subroutine calculates the sigmoid damage function
      DMGDIFF = ZERO
      DMGR=ONE-DMG
      IF (SEF.GE.SEF0) THEN
        DMG=ONE/(ONE+EXP(BETA*(SEF-PSIHALF)))
        DMGDIFF=DMG*(DMG-ONE)
        SEF0=SEF
        DMGR=ONE-DMG
      ENDIF
C
      RETURN
C
      END SUBROUTINE DAMAGE
