      SUBROUTINE DAMAGE(SEF,SEF0,DMG,DMGR,DMGDIFF,BETA,PSIHALF)
C>    VISCOUS DISSIPATION: READ STATE VARS
      IMPLICIT NONE
      INCLUDE 'param_umat.inc'
C
      DOUBLE PRECISION SEF,SEF0,DMG,DMGR,DMGDIFF,BETA,PSIHALF

C     this subroutine calculates the sigmoid damage function
      DMGDIFF = ZERO
      DMGR=ONE-DMG
      IF (SEF.GE.SEF0) THEN
        DMGR=ONE/(ONE+EXP(BETA*(SEF-PSIHALF)))
        DMGDIFF=DMGR*(DMGR-ONE)
        SEF0=SEF
        DMG=ONE-DMGR
      ENDIF
C
      RETURN
C
      END SUBROUTINE DAMAGE
