       SUBROUTINE INITIALIZE(STATEV)
C
      IMPLICIT NONE
      INCLUDE 'param_umat.inc'
C      
C      COMMON /KCOMMON/KBLOCK
C
C      DOUBLE PRECISION TIME(2),KSTEP
      INTEGER I1,POS,POS1,POS2,POS3
      DOUBLE PRECISION STATEV(NSDV)
C        DETERMINANT
        STATEV(1)=ONE
C     MAXIMUM SEF VALUE
        STATEV(3)= ZERO
C     damage 
        STATEV(4) = ZERO
C     nonlocal damage 
        STATEV(5) = ZERO
      RETURN
C
      END SUBROUTINE INITIALIZE
