       SUBROUTINE INITIALIZE(STATEV)
C
      IMPLICIT NONE
      INCLUDE 'param_umat.inc'
C
C      DOUBLE PRECISION TIME(2),KSTEP
      INTEGER I1,POS,POS1,POS2,POS3,VV
      DOUBLE PRECISION STATEV(NSDV)
C
        POS1=0
C       DETERMINANT        
          STATEV(POS1+1)=ONE
C        CONTRACTION VARIANCE
          STATEV(POS1+2)=ZERO          
C     
      RETURN
C
      END SUBROUTINE INITIALIZE
