       SUBROUTINE SLIDING(FFC,RU,FFC0,RU0,FFCMAX,FRIC,FRAC,DTIME)
C
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      DOUBLE PRECISION FFC,FFC0,RU,RU0
C
      DOUBLE PRECISION FRIC,FRAC(4),DTIME
      DOUBLE PRECISION AUX0,AUX1,AUX2,FFCMAX,ARG
C      INTEGER STATE
C     
      AUX1=FRAC(3)
      AUX0=AUX1+FRAC(4)
      AUX2=AUX0
      ARG=FFC0/FFCMAX
C
      IF(ARG.LT.AUX1) THEN
       FFC=AUX1*FFCMAX
      ELSEIF (ARG.GT.AUX2)THEN
       FFC=AUX2*FFCMAX
      ELSE
       FFC=FFC0
      ENDIF
C
      RU=RU0+DTIME*(FRIC**(-ONE))*(FFC-FFC0)
      RU0=RU
C
      RETURN
C
      END SUBROUTINE SLIDING
